name: Test Google Search

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. 檢出專案程式碼
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 安裝 Python 環境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # 3. 安裝必要依賴
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv selenium

    # 4. 安裝 Chrome 瀏覽器和驅動程式
    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo apt-get install -y google-chrome-stable
        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    # 5. 添加環境變數（模擬 .env 文件）
    - name: Set environment variables
      run: echo "SEARCH_KEYWORD=${{ secrets.SEARCH_KEYWORD }}" >> $GITHUB_ENV

    # 6. 執行測試
    - name: Run Google search test
      run: python google_search_test.py
